import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from tqdm.auto import tqdm

from ..base import BaseGenerator
from ..persistence import load_generator_state, restore_generator, save_generator_state


class SynthpopGenerator(BaseGenerator):
    """Synthpop generator using sequential decision trees.

    Fits bagged column-order models. Each bag trains one decision tree per
    column on a bootstrap of the real data. The first column in each order is
    sampled from real marginal distributions. Each following column is predicted
    from all columns to its left using a decision tree. Synthetic data is generated by
    (smoothed) sampling from the predicted leaf.

    Args:
        minibucket (int): Minimum number of samples required at a tree leaf.
            Passed to sklearn as ``min_samples_leaf``. Default: 10.
        K (int): Number of bagged feature-order models. When ``K <= 1``, the
            original feature order is used. Default: 1.
        n_jobs (int): Number of parallel jobs used during training and
            generation. Default: -1.
        tree_kwargs (dict, optional): Additional keyword arguments passed to
            each sklearn decision tree.
        honest_trees (bool): If True, fit trees with bootstrap sample weights
            but sample generated values from out-of-bag rows. Leaves with fewer
            than ``minibucket`` out-of-bag rows are collapsed upward. Default:
            False.
        cache_real_leafs (bool): If True, lazily cache real-data leaf assignments
            during non-honest generation to speed up repeated sampling at the
            cost of extra memory. Default: False.
        cache_honest_lookup (bool): If True, lazily cache honest-tree source
            lookups during generation to speed up repeated sampling at the cost
            of extra memory. Default: False.
        condition_y (bool): If True, place ``target_column`` last in every
            feature order so it is generated with all other columns as context.
            Default: False.
        target_column (str, optional): Target column used when
            ``condition_y=True``.
        smoothing (str, optional): Sampling strategy for numerical values.
            ``None``, ``"none"``, and ``"bootstrap"`` keep straightforward
            resampling. ``"histogram"`` samples from equal-width histogram
            bins. ``"kde"`` samples from a Gaussian KDE fitted to the
            source values. ``"eqf"`` samples through an
            interpolated empirical quantile function. Default: None.
        kde_kwargs (dict, optional): Optional KDE settings. Use
            ``{"bandwidth": value}`` to set an absolute bandwidth; otherwise
            Scott's rule is used. Default: None.
            Default: None.
        random_state (int): Random seed for reproducibility. Default: 0.

    Example:
        >>> import pandas as pd
        >>> from synthyverse.generators import SynthpopGenerator
        >>>
        >>> X = pd.read_csv("data.csv")
        >>> discrete_features = ["category_col"]
        >>>
        >>> generator = SynthpopGenerator(
        ...     minibucket=5,
        ...     tree_kwargs={"max_depth": 10},
        ...     random_state=42,
        ... )
        >>> generator.fit(X, discrete_features)
        >>> X_syn = generator.generate(1000)
    """

    name = "synthpop"

    def __init__(
        self,
        minibucket: int = 10,
        K: int = 1,
        n_jobs: int = -1,
        tree_kwargs: dict = None,
        honest_trees: bool = False,
        cache_real_leafs: bool = False,
        cache_honest_lookup: bool = False,
        condition_y: bool = False,
        target_column: str = None,
        smoothing: str = None,
        kde_kwargs: dict = None,
        random_state: int = 0,
    ):
        if condition_y and target_column is None:
            raise ValueError("target_column must be passed when condition_y=True.")

        self.minibucket = int(minibucket)
        self.K = int(K)
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.honest_trees = bool(honest_trees)
        self.cache_real_leafs = bool(cache_real_leafs)
        self.cache_honest_lookup = bool(cache_honest_lookup)
        self.condition_y = bool(condition_y)
        self.target_column = target_column
        self.tree_kwargs = {} if tree_kwargs is None else dict(tree_kwargs)
        self.tree_kwargs["min_samples_leaf"] = self.minibucket
        self.tree_kwargs["random_state"] = random_state
        self.smoothing = self._normalize_smoothing(smoothing)
        self.kde_kwargs = {} if kde_kwargs is None else dict(kde_kwargs)
        self._reset_runtime_caches()

    def _fit(self, X: pd.DataFrame, discrete_features: list):
        self.columns = X.columns.tolist()
        if self.condition_y and self.target_column not in self.columns:
            raise ValueError(f"target_column '{self.target_column}' is not in X.")

        self.discrete_features = [
            col for col in self.columns if col in discrete_features
        ]
        self.discrete_idx = {
            i for i, col in enumerate(self.columns) if col in self.discrete_features
        }

        X_fit = X.copy()
        if self.discrete_features:
            self.encoder = OrdinalEncoder()
            X_fit[self.discrete_features] = self.encoder.fit_transform(
                X_fit[self.discrete_features]
            )
        else:
            self.encoder = None

        X_np = X_fit.to_numpy(dtype=float)
        n_models = max(1, self.K)
        n_cols = len(self.columns)
        self.marginal_values = [X_np[:, i].copy() for i in range(n_cols)]
        self.order_seeds = None
        self.weight_seeds = None
        if self.random_state is None:
            rng = np.random.default_rng()
            high = np.iinfo(np.uint32).max
            self.order_seeds = rng.integers(high, size=n_models).tolist()
            self.weight_seeds = rng.integers(high, size=n_models).tolist()
        self.models = [{} for _ in range(n_models)]

        def fit_model(model_idx):
            order = self._feature_order(model_idx)
            sample_weight = self._sample_weight(model_idx)
            if (
                self.honest_trees
                and np.count_nonzero(sample_weight == 0) < self.minibucket
            ):
                raise ValueError(
                    "honest_trees=True requires at least minibucket out-of-bag "
                    "rows in every bootstrap sample."
                )
            columns = {}
            for target_idx, target in enumerate(order[1:], start=1):
                predictors = order[:target_idx]
                tree_class = (
                    DecisionTreeClassifier
                    if target in self.discrete_idx
                    else DecisionTreeRegressor
                )
                tree = tree_class(**self.tree_kwargs.copy())
                tree.fit(
                    X_np[:, predictors],
                    X_np[:, target],
                    sample_weight=sample_weight,
                )
                columns[target] = tree
            return model_idx, {"columns": columns}

        fits = Parallel(
            n_jobs=self.n_jobs, prefer="threads", return_as="generator_unordered"
        )(delayed(fit_model)(model_idx) for model_idx in range(n_models))
        models = [None] * n_models
        for model_idx, model in tqdm(
            fits, total=n_models, desc="Training synthpop", unit="model"
        ):
            models[model_idx] = model
        self.models = models

        self._reset_runtime_caches()
        return self

    def _generate(self, n: int):
        self._ensure_runtime_caches()
        sizes = np.full(len(self.models), n // len(self.models), dtype=int)
        sizes[: n % len(self.models)] += 1
        show_column_progress = self.n_jobs == 1 or np.count_nonzero(sizes) == 1
        chunks = Parallel(n_jobs=self.n_jobs, prefer="threads", return_as="generator")(
            delayed(self._generate_model)(model_idx, size, show_column_progress)
            for model_idx, size in enumerate(sizes)
            if size > 0
        )
        if not show_column_progress:
            chunks = tqdm(
                chunks,
                total=int(np.count_nonzero(sizes)),
                desc="Generating synthpop",
                unit="model",
            )
        chunks = list(chunks)
        syn = (
            pd.concat(chunks, ignore_index=True)
            if chunks
            else pd.DataFrame(columns=self.columns)
        )

        if self.discrete_features and len(syn) > 0:
            syn[self.discrete_features] = self.encoder.inverse_transform(
                syn[self.discrete_features]
            )

        return syn[self.columns]

    def _generate_model(self, model_idx: int, n: int, show_progress: bool = False):
        model = self.models[model_idx]
        order = self._feature_order(model_idx)
        sample_weight = self._sample_weight(model_idx)
        source_idx = np.flatnonzero(sample_weight == 0) if self.honest_trees else None
        rng = np.random.default_rng(self._derive_seed(2, model_idx))
        syn = np.empty((n, len(self.columns)))

        columns = enumerate(order)
        if show_progress:
            columns = tqdm(
                columns,
                total=len(order),
                desc="Generating synthpop",
                unit="column",
            )

        for target_idx, col in columns:
            if target_idx == 0:
                values = self.marginal_values[col]
                syn[:, col] = self._sample_values(
                    values if source_idx is None else values[source_idx],
                    size=n,
                    rng=rng,
                    smooth=col not in self.discrete_idx,
                    sample_weight=sample_weight if source_idx is None else None,
                )
                continue

            predictors = order[:target_idx]
            tree = self._column_tree(model, col)
            leaves = tree.apply(syn[:, predictors])

            sampled = np.empty(n)
            if source_idx is None:
                if self.cache_real_leafs:
                    cache = self._real_leaf_cache[model_idx]
                    if col not in cache:
                        cache[col] = tree.apply(
                            np.column_stack(
                                [self.marginal_values[p] for p in predictors]
                            )
                        )
                    train_leaves = cache[col]
                else:
                    train_leaves = tree.apply(
                        np.column_stack([self.marginal_values[p] for p in predictors])
                    )
                for leaf in np.unique(leaves):
                    mask = leaves == leaf
                    leaf_source_idx = np.flatnonzero(train_leaves == leaf)
                    sampled[mask] = self._sample_values(
                        self.marginal_values[col][leaf_source_idx],
                        size=mask.sum(),
                        rng=rng,
                        smooth=col not in self.discrete_idx,
                        sample_weight=sample_weight[leaf_source_idx],
                    )
            else:
                lookup_cache = None
                if self.cache_honest_lookup:
                    lookup_cache = self._honest_lookup_cache[model_idx].setdefault(
                        col, {}
                    )
                source_X = (
                    None
                    if lookup_cache is not None and "counts" in lookup_cache
                    else np.column_stack(
                        [self.marginal_values[p][source_idx] for p in predictors]
                    )
                )
                leaf_to_node, node_to_source = self._honest_sources(
                    tree, source_X, source_idx, leaves, lookup_cache
                )
                for leaf in np.unique(leaves):
                    mask = leaves == leaf
                    leaf_source_idx = node_to_source[leaf_to_node[int(leaf)]]
                    sampled[mask] = self._sample_values(
                        self.marginal_values[col][leaf_source_idx],
                        size=mask.sum(),
                        rng=rng,
                        smooth=col not in self.discrete_idx,
                    )
            syn[:, col] = sampled

        return pd.DataFrame(syn, columns=self.columns)

    def _honest_sources(self, tree, source_X, source_idx, leaves, lookup_cache=None):
        if lookup_cache is not None and "counts" in lookup_cache:
            counts = lookup_cache["counts"]
            parent = lookup_cache["parent"]
            node_to_source = lookup_cache["node_to_source"]
            path = None
        else:
            path = tree.decision_path(source_X).tocsc()
            counts = np.diff(path.indptr)
            if counts[0] < self.minibucket:
                raise ValueError(
                    "honest_trees=True requires at least minibucket out-of-bag rows."
                )

            tree_ = tree.tree_
            parent = np.full(tree_.node_count, -1, dtype=np.int64)
            for node, (left, right) in enumerate(
                zip(tree_.children_left, tree_.children_right)
            ):
                if left != -1:
                    parent[left] = node
                    parent[right] = node

            if lookup_cache is None:
                node_to_source = {}
            else:
                node_to_source = {
                    node: source_idx[
                        path.indices[path.indptr[node] : path.indptr[node + 1]]
                    ]
                    for node in range(tree_.node_count)
                    if counts[node] > 0
                }
                lookup_cache.update(
                    {
                        "counts": counts,
                        "parent": parent,
                        "node_to_source": node_to_source,
                    }
                )

        leaf_to_node = {}
        for leaf in np.unique(leaves):
            node = int(leaf)
            while counts[node] < self.minibucket:
                node = int(parent[node])
            leaf_to_node[int(leaf)] = node
            if node not in node_to_source:
                node_to_source[node] = source_idx[
                    path.indices[path.indptr[node] : path.indptr[node + 1]]
                ]

        return leaf_to_node, node_to_source

    def _reset_runtime_caches(self):
        self._real_leaf_cache = [{} for _ in range(len(getattr(self, "models", [])))]
        self._honest_lookup_cache = [
            {} for _ in range(len(getattr(self, "models", [])))
        ]

    def _ensure_runtime_caches(self):
        if len(getattr(self, "_real_leaf_cache", [])) != len(self.models):
            self._reset_runtime_caches()

    def __post_load__(self):
        self.cache_real_leafs = bool(getattr(self, "cache_real_leafs", False))
        self.cache_honest_lookup = bool(getattr(self, "cache_honest_lookup", False))
        self._reset_runtime_caches()

    def _feature_order(self, model_idx):
        n_cols = len(self.columns)
        if self.K <= 1:
            order = list(range(n_cols))
            if self.condition_y:
                target = self.columns.index(self.target_column)
                order.remove(target)
                order.append(target)
            return order

        model = self.models[model_idx]
        if "order" in model:
            return model["order"]
        seed = (
            self._derive_seed(0, model_idx)
            if self.random_state is not None
            else self.order_seeds[model_idx]
        )
        order = np.random.default_rng(seed).permutation(n_cols).tolist()
        if self.condition_y:
            target = self.columns.index(self.target_column)
            order.remove(target)
            order.append(target)
        return order

    def _sample_weight(self, model_idx):
        model = self.models[model_idx]
        if "sample_weight" in model:
            return model["sample_weight"]
        n_rows = len(self.marginal_values[0])
        seed = (
            self._derive_seed(1, model_idx)
            if self.random_state is not None
            else self.weight_seeds[model_idx]
        )
        return (
            np.random.default_rng(seed)
            .multinomial(n_rows, np.full(n_rows, 1 / n_rows))
            .astype(float)
        )

    @staticmethod
    def _column_tree(model, col):
        column_model = model["columns"][col]
        return column_model["tree"] if isinstance(column_model, dict) else column_model

    @staticmethod
    def _normalize_smoothing(smoothing):
        if smoothing is None:
            return "bootstrap"

        normalized = str(smoothing).lower()
        if normalized in {"none", "bootstrap"}:
            return "bootstrap"
        if normalized in {"histogram", "kde", "eqf"}:
            return normalized

        raise ValueError(
            "smoothing must be one of None, 'none', 'bootstrap', 'histogram', "
            "'kde', or 'eqf'."
        )

    def _derive_seed(self, *parts):
        if self.random_state is None:
            return None

        entropy = [int(self.random_state) & 0xFFFFFFFF]
        entropy.extend(int(part) & 0xFFFFFFFF for part in parts)
        seed = np.random.SeedSequence(entropy).generate_state(1, dtype=np.uint32)[0]
        return int(seed)

    def _fit_value_sampler(self, values, sample_weight=None):
        numeric_values = np.asarray(values, dtype=float)

        if len(numeric_values) <= 1:
            return None

        if self.smoothing == "histogram":
            unique_values = np.unique(numeric_values)
            if len(unique_values) < 64:
                return {"kind": "unique", "values": unique_values}

            counts, edges = np.histogram(numeric_values, bins=64)
            return {
                "kind": "histogram",
                "counts": counts,
                "edges": edges,
                "values": numeric_values,
            }

        if self.smoothing == "eqf":
            n_quantiles = min(int(1e9), len(numeric_values))
            references = np.linspace(0, 1, n_quantiles, endpoint=True)
            quantiles = (
                np.sort(numeric_values)
                if n_quantiles == len(numeric_values)
                else np.nanpercentile(numeric_values, references * 100)
            )
            return {
                "kind": "eqf",
                "references": references,
                "quantiles": np.maximum.accumulate(quantiles),
            }

        if self.smoothing == "kde":
            p = None
            n_eff = len(numeric_values)
            if sample_weight is not None and np.sum(sample_weight) > 0:
                p = sample_weight / np.sum(sample_weight)
                n_eff = 1 / np.sum(p * p)
                mean = np.average(numeric_values, weights=p)
                std = np.sqrt(np.average((numeric_values - mean) ** 2, weights=p))
            else:
                std = np.std(numeric_values, ddof=1)

            bandwidth = self.kde_kwargs.get("bandwidth")
            bandwidth = std * n_eff**-0.2 if bandwidth is None else float(bandwidth)
            if not np.isfinite(bandwidth) or bandwidth <= 0:
                return None

            return {
                "kind": "kde",
                "values": numeric_values,
                "p": p,
                "bandwidth": bandwidth,
            }

        return None

    def _sample_values(
        self,
        values,
        size,
        rng,
        smooth=False,
        sample_weight=None,
    ):
        if self.smoothing == "bootstrap" or not smooth or size == 0:
            p = None
            if sample_weight is not None and np.sum(sample_weight) > 0:
                p = sample_weight / np.sum(sample_weight)
            return rng.choice(values, size=size, replace=True, p=p)

        sampler = self._fit_value_sampler(values, sample_weight=sample_weight)
        if sampler is None:
            p = None
            if sample_weight is not None and np.sum(sample_weight) > 0:
                p = sample_weight / np.sum(sample_weight)
            return rng.choice(values, size=size, replace=True, p=p)

        if sampler["kind"] == "unique":
            sampled = rng.choice(sampler["values"], size=size, replace=True)
        elif sampler["kind"] == "histogram":
            sampled = self._sample_histogram(sampler, size, rng)
        elif sampler["kind"] == "eqf":
            if "transformer" in sampler:
                sampled = (
                    sampler["transformer"]
                    .inverse_transform(rng.random((size, 1)))
                    .ravel()
                )
            else:
                sampled = np.interp(
                    rng.random(size), sampler["references"], sampler["quantiles"]
                )
        elif sampler["kind"] == "kde":
            sampled = rng.choice(
                sampler["values"], size=size, replace=True, p=sampler["p"]
            ) + rng.normal(0, sampler["bandwidth"], size=size)
        else:
            sampled = rng.choice(values, size=size, replace=True)

        return sampled

    @staticmethod
    def _sample_histogram(sampler, size, rng):
        counts = sampler["counts"]
        bins = rng.choice(len(counts), size=size, replace=True, p=counts / counts.sum())
        sampled = np.empty(size)

        for bin_idx in np.unique(bins):
            mask = bins == bin_idx
            left, right = sampler["edges"][bin_idx : bin_idx + 2]
            values = sampler["values"]
            if bin_idx == len(counts) - 1:
                bin_values = values[(values >= left) & (values <= right)]
            else:
                bin_values = values[(values >= left) & (values < right)]

            unique_values = np.unique(bin_values)
            sampled[mask] = (
                unique_values[0]
                if len(unique_values) == 1
                else rng.uniform(left, right, size=mask.sum())
            )

        return sampled

    def save(self, path):
        state = self.__dict__.copy()
        state.pop("marginal_samplers", None)
        state.pop("_real_leaf_cache", None)
        state.pop("_honest_lookup_cache", None)
        state["models"] = [
            {
                "columns": {
                    col: self._column_tree(model, col) for col in model["columns"]
                }
            }
            for model in self.models
        ]
        return save_generator_state(path, state)

    @classmethod
    def load(cls, path):
        return restore_generator(cls, load_generator_state(path))
