import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from tqdm.auto import tqdm

from ..base import BaseGenerator
from ..persistence import load_generator_state, restore_generator, save_generator_state


class SynthpopGenerator(BaseGenerator):
    """Synthpop generator using sequential decision trees.

    Fits bagged column-order models. Each bag trains one decision tree per
    column on a random subsample of the real data. The first column in each
    order is sampled from real marginal distributions. Each following column is
    predicted from all columns to its left using a decision tree. Synthetic data
    is generated by (smoothed) sampling from the predicted leaf.

    Python implementation from scratch based on the method described in the paper: "synthpop: Bespoke creation of synthetic data in R" by Nowok et al. (2016).

    Args:
        minibucket (int): Minimum number of split-learning samples required at
            a tree leaf. Passed to sklearn as ``min_samples_leaf``. Default: 10.
        minibucket_sampling (int): Minimum number of source samples used when
            sampling from honest-tree leaves. Leaves with fewer source samples
            are collapsed upward. Default: 5.
        K (int): Number of bagged feature-order models. When ``K < 1``, the
            original feature order is used. Default: 100.
        n_jobs (int): Number of parallel jobs used during training and
            generation. Default: -1.
        tree_kwargs (dict, optional): Additional keyword arguments passed to
            each sklearn decision tree.
        subsample (float): Fraction of rows used to train each tree when
            ``0 < subsample < 1``. Values outside that interval use all rows,
            or a full-size bootstrap sample when ``subsample_with_replacement``
            is True. Default: 1.0.
        subsample_with_replacement (bool): If True, train each tree on a
            bootstrap subsample and use out-of-bag rows for honest sampling.
            If False, train on a subsample without replacement. Default: True.
        honest_trees (bool): If True, sample from out-of-bag rows for bootstrap
            trees or unused rows for subsampling without replacement. Default:
            True.
        cache_real_leafs (bool): If True, lazily cache real-data leaf assignments
            during non-honest generation to speed up repeated sampling at the
            cost of extra memory. Default: False.
        cache_honest_lookup (bool): If True, lazily cache honest-tree source
            lookups during generation to speed up repeated sampling at the cost
            of extra memory. Default: False.
        condition_y (str, optional): Place ``target_column`` at ``"first"`` or
            ``"last"`` in every feature order. ``None`` disables conditioning.
            Default: None.
        target_column (str, optional): Target column used when
            ``condition_y`` is not ``None``.
        smoothing (str, optional): Sampling strategy for numerical values.
            ``None``, ``"none"``, and ``"bootstrap"`` keep straightforward
            resampling. ``"histogram"`` samples from equal-width histogram
            bins. ``"kde"`` samples from a Gaussian KDE fitted to the
            source values. ``"eqf"`` samples through an
            interpolated empirical quantile function. Default: None.
        kde_kwargs (dict, optional): Optional KDE settings. Use
            ``{"bandwidth": value}`` to set an absolute bandwidth; otherwise
            Scott's rule is used. Default: None.
            Default: None.
        random_state (int): Random seed for reproducibility. Default: 0.

    Example:
        >>> import pandas as pd
        >>> from synthyverse.generators import SynthpopGenerator
        >>>
        >>> X = pd.read_csv("data.csv")
        >>> discrete_features = ["category_col"]
        >>>
        >>> generator = SynthpopGenerator(
        ...     minibucket=5,
        ...     minibucket_sampling=5,
        ...     tree_kwargs={"max_depth": 10},
        ...     random_state=42,
        ... )
        >>> generator.fit(X, discrete_features)
        >>> X_syn = generator.generate(1000)
    """

    name = "synthpop"

    def __init__(
        self,
        minibucket: int = 10,
        minibucket_sampling: int = 3,
        K: int = 100,
        n_jobs: int = -1,
        tree_kwargs: dict = None,
        subsample: float = 1.0,
        subsample_with_replacement: bool = True,
        honest_trees: bool = True,
        cache_real_leafs: bool = False,
        cache_honest_lookup: bool = False,
        condition_y: str = None,
        target_column: str = None,
        smoothing: str = None,
        kde_kwargs: dict = None,
        random_state: int = 0,
    ):
        if condition_y not in {None, "first", "last"}:
            raise ValueError("condition_y must be one of None, 'first', or 'last'.")
        if condition_y is not None and target_column is None:
            raise ValueError("target_column must be passed when condition_y is set.")

        self.minibucket = int(minibucket)
        self.minibucket_sampling = int(minibucket_sampling)
        self.K = int(K)
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.subsample = float(subsample)
        self.subsample_with_replacement = bool(subsample_with_replacement)
        self.honest_trees = bool(honest_trees)
        if (
            self.honest_trees
            and not self.subsample_with_replacement
            and (self.subsample <= 0 or self.subsample >= 1)
        ):
            raise ValueError(
                "honest_trees=True with subsample_with_replacement=False "
                "requires 0 < subsample < 1."
            )
        self.cache_real_leafs = bool(cache_real_leafs)
        self.cache_honest_lookup = bool(cache_honest_lookup)
        self.condition_y = condition_y
        self.target_column = target_column
        self.tree_kwargs = {} if tree_kwargs is None else dict(tree_kwargs)
        self.tree_kwargs["random_state"] = random_state
        self.smoothing = self._normalize_smoothing(smoothing)
        self.kde_kwargs = {} if kde_kwargs is None else dict(kde_kwargs)
        self._reset_runtime_caches()

    def _fit(self, X: pd.DataFrame, discrete_features: list):
        self.columns = X.columns.tolist()
        if self.condition_y is not None and self.target_column not in self.columns:
            raise ValueError(f"target_column '{self.target_column}' is not in X.")

        self.discrete_features = [
            col for col in self.columns if col in discrete_features
        ]
        self.discrete_idx = {
            i for i, col in enumerate(self.columns) if col in self.discrete_features
        }

        X_fit = X.copy()
        if self.discrete_features:
            self.encoder = OrdinalEncoder()
            X_fit[self.discrete_features] = self.encoder.fit_transform(
                X_fit[self.discrete_features]
            )
        else:
            self.encoder = None

        X_np = X_fit.to_numpy(dtype=float)
        n_models = max(1, self.K)
        n_cols = len(self.columns)
        self.marginal_values = [X_np[:, i] for i in range(n_cols)]
        self.order_seeds = None
        self.split_seeds = None
        if self.random_state is None:
            rng = np.random.default_rng()
            high = np.iinfo(np.uint32).max
            self.order_seeds = rng.integers(high, size=n_models).tolist()
            self.split_seeds = rng.integers(high, size=n_models).tolist()
        self.models = [{} for _ in range(n_models)]

        def fit_model(model_idx):
            order = self._feature_order(model_idx)
            train_idx = self._train_indices(model_idx)
            source_idx = (
                self._source_indices_from_train(train_idx)
                if self.honest_trees
                else None
            )
            if source_idx is not None and len(source_idx) < self.minibucket_sampling:
                raise ValueError(
                    "honest_trees=True requires at least minibucket_sampling "
                    "unused or out-of-bag rows."
                )
            X_train = X_np if train_idx is None else X_np[train_idx]
            columns = {}
            for target_idx, target in enumerate(order[1:], start=1):
                predictors = order[:target_idx]
                tree_class = (
                    DecisionTreeClassifier
                    if target in self.discrete_idx
                    else DecisionTreeRegressor
                )
                tree_kwargs = self.tree_kwargs.copy()
                tree_kwargs["min_samples_leaf"] = self.minibucket
                tree = tree_class(**tree_kwargs)
                tree.fit(X_train[:, predictors], X_train[:, target])
                columns[target] = tree
            return model_idx, {"columns": columns}

        fits = Parallel(
            n_jobs=self.n_jobs, prefer="threads", return_as="generator_unordered"
        )(delayed(fit_model)(model_idx) for model_idx in range(n_models))
        models = [None] * n_models
        for model_idx, model in tqdm(
            fits, total=n_models, desc="Training synthpop", unit="model"
        ):
            models[model_idx] = model
        self.models = models

        self._reset_runtime_caches()
        return self

    def _generate(self, n: int):
        self._ensure_runtime_caches()
        sizes = np.full(len(self.models), n // len(self.models), dtype=int)
        sizes[: n % len(self.models)] += 1
        show_column_progress = self.n_jobs == 1 or np.count_nonzero(sizes) == 1
        chunks = Parallel(n_jobs=self.n_jobs, prefer="threads", return_as="generator")(
            delayed(self._generate_model)(model_idx, size, show_column_progress)
            for model_idx, size in enumerate(sizes)
            if size > 0
        )
        if not show_column_progress:
            chunks = tqdm(
                chunks,
                total=int(np.count_nonzero(sizes)),
                desc="Generating synthpop",
                unit="model",
            )
        chunks = list(chunks)
        syn = pd.DataFrame(
            np.vstack(chunks) if chunks else np.empty((0, len(self.columns))),
            columns=self.columns,
        )

        if self.discrete_features and len(syn) > 0:
            syn[self.discrete_features] = self.encoder.inverse_transform(
                syn[self.discrete_features]
            )

        return syn[self.columns]

    def _generate_model(self, model_idx: int, n: int, show_progress: bool = False):
        model = self.models[model_idx]
        order = self._feature_order(model_idx)
        train_idx = self._train_indices(model_idx)
        source_idx = (
            self._source_indices_from_train(train_idx) if self.honest_trees else None
        )
        rng = np.random.default_rng(self._derive_seed(2, model_idx))
        syn = np.empty((n, len(self.columns)))

        columns = enumerate(order)
        if show_progress:
            columns = tqdm(
                columns,
                total=len(order),
                desc="Generating synthpop",
                unit="column",
            )

        for target_idx, col in columns:
            if target_idx == 0:
                values = self.marginal_values[col]
                syn[:, col] = self._sample_values(
                    values if source_idx is None else values[source_idx],
                    size=n,
                    rng=rng,
                    smooth=col not in self.discrete_idx,
                )
                continue

            predictors = order[:target_idx]
            tree = self._column_tree(model, col)
            leaves = tree.apply(syn[:, predictors])
            leaf_values, row_order, row_starts, row_ends = self._group_indices(leaves)

            sampled = np.empty(n)
            if source_idx is None:
                if self.cache_real_leafs:
                    cache = self._real_leaf_cache[model_idx]
                    if col not in cache:
                        cache[col] = self._group_indices(
                            tree.apply(
                                np.column_stack(
                                    [self.marginal_values[p] for p in predictors]
                                )
                            )
                        )
                    train_values, train_order, train_starts, train_ends = cache[col]
                else:
                    train_values, train_order, train_starts, train_ends = (
                        self._group_indices(
                            tree.apply(
                                np.column_stack(
                                    [self.marginal_values[p] for p in predictors]
                                )
                            )
                        )
                    )
                for leaf, row_start, row_end in zip(leaf_values, row_starts, row_ends):
                    train_pos = np.searchsorted(train_values, leaf)
                    source_start = train_starts[train_pos]
                    source_end = train_ends[train_pos]
                    rows = row_order[row_start:row_end]
                    sampled[rows] = self._sample_values(
                        self.marginal_values[col][train_order[source_start:source_end]],
                        size=len(rows),
                        rng=rng,
                        smooth=col not in self.discrete_idx,
                    )
            else:
                lookup_cache = None
                if self.cache_honest_lookup:
                    lookup_cache = self._honest_lookup_cache[model_idx].setdefault(
                        col, {}
                    )
                source_X = (
                    None
                    if lookup_cache is not None and "counts" in lookup_cache
                    else np.column_stack(
                        [self.marginal_values[p][source_idx] for p in predictors]
                    )
                )
                leaf_to_node, node_to_source = self._honest_sources(
                    tree, source_X, source_idx, leaf_values, lookup_cache
                )
                for leaf, row_start, row_end in zip(leaf_values, row_starts, row_ends):
                    rows = row_order[row_start:row_end]
                    leaf_source_idx = node_to_source[leaf_to_node[int(leaf)]]
                    sampled[rows] = self._sample_values(
                        self.marginal_values[col][leaf_source_idx],
                        size=len(rows),
                        rng=rng,
                        smooth=col not in self.discrete_idx,
                    )
            syn[:, col] = sampled

        return syn

    def _honest_sources(self, tree, source_X, source_idx, leaves, lookup_cache=None):
        if lookup_cache is not None and "counts" in lookup_cache:
            counts = lookup_cache["counts"]
            parent = lookup_cache["parent"]
            node_to_source = lookup_cache["node_to_source"]
            path = lookup_cache["path"]
        else:
            path = tree.decision_path(source_X).tocsc()
            counts = np.diff(path.indptr)
            if counts[0] < self.minibucket_sampling:
                raise ValueError(
                    "honest_trees=True requires at least minibucket_sampling "
                    "unused or out-of-bag rows."
                )

            tree_ = tree.tree_
            parent = np.full(tree_.node_count, -1, dtype=np.int64)
            for node, (left, right) in enumerate(
                zip(tree_.children_left, tree_.children_right)
            ):
                if left != -1:
                    parent[left] = node
                    parent[right] = node

            if lookup_cache is None:
                node_to_source = {}
            else:
                node_to_source = {}
                lookup_cache.update(
                    {
                        "counts": counts,
                        "parent": parent,
                        "node_to_source": node_to_source,
                        "path": path,
                    }
                )

        leaf_to_node = {}
        for leaf in leaves:
            node = int(leaf)
            while counts[node] < self.minibucket_sampling:
                node = int(parent[node])
            leaf_to_node[int(leaf)] = node
            if node not in node_to_source:
                node_to_source[node] = source_idx[
                    path.indices[path.indptr[node] : path.indptr[node + 1]]
                ]

        return leaf_to_node, node_to_source

    def _reset_runtime_caches(self):
        self._real_leaf_cache = [{} for _ in range(len(getattr(self, "models", [])))]
        self._honest_lookup_cache = [
            {} for _ in range(len(getattr(self, "models", [])))
        ]

    def _ensure_runtime_caches(self):
        if len(getattr(self, "_real_leaf_cache", [])) != len(self.models):
            self._reset_runtime_caches()

    def __post_load__(self):
        self.subsample = float(self.subsample)
        self.subsample_with_replacement = bool(
            getattr(self, "subsample_with_replacement", True)
        )
        self.honest_trees = bool(getattr(self, "honest_trees", True))
        if (
            self.honest_trees
            and not self.subsample_with_replacement
            and (self.subsample <= 0 or self.subsample >= 1)
        ):
            raise ValueError(
                "honest_trees=True with subsample_with_replacement=False "
                "requires 0 < subsample < 1."
            )
        self.cache_real_leafs = bool(getattr(self, "cache_real_leafs", False))
        self.cache_honest_lookup = bool(getattr(self, "cache_honest_lookup", False))
        self._reset_runtime_caches()

    def _feature_order(self, model_idx):
        n_cols = len(self.columns)
        if self.K < 1:
            order = list(range(n_cols))
            if self.condition_y is not None:
                order = self._condition_order(order)
            return order

        model = self.models[model_idx]
        if "order" in model:
            return model["order"]
        seed = (
            self._derive_seed(0, model_idx)
            if self.random_state is not None
            else self.order_seeds[model_idx]
        )
        order = np.random.default_rng(seed).permutation(n_cols).tolist()
        if self.condition_y is not None:
            order = self._condition_order(order)
        return order

    def _condition_order(self, order):
        target = self.columns.index(self.target_column)
        order.remove(target)
        if self.condition_y == "first":
            order.insert(0, target)
        else:
            order.append(target)
        return order

    def _train_indices(self, model_idx):
        if not self.subsample_with_replacement and (
            self.subsample <= 0 or self.subsample >= 1
        ):
            return None

        n_rows = len(self.marginal_values[0])
        n_train = int(n_rows * self.subsample) if 0 < self.subsample < 1 else n_rows
        if n_train <= 0:
            raise ValueError("subsample leaves no rows for tree training.")

        seed = (
            self._derive_seed(1, model_idx)
            if self.random_state is not None
            else self.split_seeds[model_idx]
        )
        sampled = np.random.default_rng(seed).choice(
            n_rows, n_train, replace=self.subsample_with_replacement
        )
        return sampled

    def _source_indices(self, model_idx):
        train_idx = self._train_indices(model_idx)
        return self._source_indices_from_train(train_idx)

    def _source_indices_from_train(self, train_idx):
        if train_idx is None:
            return None

        selected = np.zeros(len(self.marginal_values[0]), dtype=bool)
        selected[train_idx] = True
        return np.flatnonzero(~selected)

    @staticmethod
    def _group_indices(values):
        order = np.argsort(values, kind="stable")
        sorted_values = values[order]
        unique, starts = np.unique(sorted_values, return_index=True)
        ends = np.r_[starts[1:], len(values)]
        return unique, order, starts, ends

    @staticmethod
    def _column_tree(model, col):
        column_model = model["columns"][col]
        return column_model["tree"] if isinstance(column_model, dict) else column_model

    @staticmethod
    def _normalize_smoothing(smoothing):
        if smoothing is None:
            return "bootstrap"

        normalized = str(smoothing).lower()
        if normalized in {"none", "bootstrap"}:
            return "bootstrap"
        if normalized in {"histogram", "kde", "eqf"}:
            return normalized

        raise ValueError(
            "smoothing must be one of None, 'none', 'bootstrap', 'histogram', "
            "'kde', or 'eqf'."
        )

    def _derive_seed(self, *parts):
        if self.random_state is None:
            return None

        entropy = [int(self.random_state) & 0xFFFFFFFF]
        entropy.extend(int(part) & 0xFFFFFFFF for part in parts)
        seed = np.random.SeedSequence(entropy).generate_state(1, dtype=np.uint32)[0]
        return int(seed)

    def _fit_value_sampler(self, values):
        numeric_values = np.asarray(values, dtype=float)

        if len(numeric_values) <= 1:
            return None

        if self.smoothing == "histogram":
            unique_values = np.unique(numeric_values)
            if len(unique_values) < 64:
                return {"kind": "unique", "values": unique_values}

            counts, edges = np.histogram(numeric_values, bins=64)
            return {
                "kind": "histogram",
                "counts": counts,
                "edges": edges,
                "values": numeric_values,
            }

        if self.smoothing == "eqf":
            n_quantiles = min(int(1e9), len(numeric_values))
            references = np.linspace(0, 1, n_quantiles, endpoint=True)
            quantiles = (
                np.sort(numeric_values)
                if n_quantiles == len(numeric_values)
                else np.nanpercentile(numeric_values, references * 100)
            )
            return {
                "kind": "eqf",
                "references": references,
                "quantiles": np.maximum.accumulate(quantiles),
            }

        if self.smoothing == "kde":
            n_eff = len(numeric_values)
            std = np.std(numeric_values, ddof=1)

            bandwidth = self.kde_kwargs.get("bandwidth")
            bandwidth = std * n_eff**-0.2 if bandwidth is None else float(bandwidth)
            if not np.isfinite(bandwidth) or bandwidth <= 0:
                return None

            return {
                "kind": "kde",
                "values": numeric_values,
                "bandwidth": bandwidth,
            }

        return None

    def _sample_values(
        self,
        values,
        size,
        rng,
        smooth=False,
    ):
        if self.smoothing == "bootstrap" or not smooth or size == 0:
            return rng.choice(values, size=size, replace=True)

        sampler = self._fit_value_sampler(values)
        if sampler is None:
            return rng.choice(values, size=size, replace=True)

        if sampler["kind"] == "unique":
            sampled = rng.choice(sampler["values"], size=size, replace=True)
        elif sampler["kind"] == "histogram":
            sampled = self._sample_histogram(sampler, size, rng)
        elif sampler["kind"] == "eqf":
            if "transformer" in sampler:
                sampled = (
                    sampler["transformer"]
                    .inverse_transform(rng.random((size, 1)))
                    .ravel()
                )
            else:
                sampled = np.interp(
                    rng.random(size), sampler["references"], sampler["quantiles"]
                )
        elif sampler["kind"] == "kde":
            sampled = rng.choice(
                sampler["values"], size=size, replace=True
            ) + rng.normal(0, sampler["bandwidth"], size=size)
        else:
            sampled = rng.choice(values, size=size, replace=True)

        return sampled

    @staticmethod
    def _sample_histogram(sampler, size, rng):
        counts = sampler["counts"]
        bins = rng.choice(len(counts), size=size, replace=True, p=counts / counts.sum())
        sampled = np.empty(size)

        for bin_idx in np.unique(bins):
            mask = bins == bin_idx
            left, right = sampler["edges"][bin_idx : bin_idx + 2]
            values = sampler["values"]
            if bin_idx == len(counts) - 1:
                bin_values = values[(values >= left) & (values <= right)]
            else:
                bin_values = values[(values >= left) & (values < right)]

            unique_values = np.unique(bin_values)
            sampled[mask] = (
                unique_values[0]
                if len(unique_values) == 1
                else rng.uniform(left, right, size=mask.sum())
            )

        return sampled

    def save(self, path):
        state = self.__dict__.copy()
        state.pop("marginal_samplers", None)
        state.pop("_real_leaf_cache", None)
        state.pop("_honest_lookup_cache", None)
        state["models"] = [
            {
                "columns": {
                    col: self._column_tree(model, col) for col in model["columns"]
                }
            }
            for model in self.models
        ]
        return save_generator_state(path, state)

    @classmethod
    def load(cls, path):
        return restore_generator(cls, load_generator_state(path))
